version: '2'
services:
  webserver:
    image: phpstorm/php-apache:7.4-xdebug2.9
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal